title: NemoVR-Viewer
description: Fish tracking visualization and DeepLabCut analysis
remote_theme: just-the-docs/just-the-docs

plugins:
  - jekyll-remote-theme

header_pages:
  - installation.md
  - usage.md
  - settings.md
  - screenshots.md
  - videos.md